language: android
jdk: oraclejdk7

android:
  # To get available components, use the following command:
  # > android list sdk --no-ui --all --extended
  components:
  - build-tools-22.0.1
  - android-22
  - extra-android-support
  - extra-android-m2repository

cache:
  directories:
  - ~/.gradle/caches/modules-2/files-2.1
  - ~/.gradle/caches/modules-2/metadata-2.14
